name: TekkitCustomizer
main: me.ryanhamshire.TekkitCustomizer.TekkitCustomizer
softdepend: [Multiverse-Core, My Worlds, Transporter, MystCraft]
version: 1.5.2
commands:
   blockinfo:
      description: Provides type ID and damage information for a material in the world or in hand.
      usage: /BlockInfo
      permission: tekkitcustomizer.blockinfo   
   reloadbanneditems:
      description: Reloads the banned item list from the config file.
      usage: /ReloadBannedItems
      permission: tekkitcustomizer.reload
permissions:
    tekkitcustomizer.admin.*:
        description: Grants all administrative privileges.
        children:
            tekkitcustomizer.blockinfo: true
            tekkitcustomizer.reload: true
    tekkitcustomizer.*:
        description: Grants permission to bypass all bans.
        default: op
    tekkitcustomizer.blockinfo:
        description: Grants permission to use /BlockInfo.
        default: op
    tekkitcustomizer.reload:
        description: Grants permission to use /ReloadBannedItems.
        default: op